=== jeasonyoung/studentbehaviors/src/main/resources/iPowerSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
	targetNamespace="http://ipower.org/" xmlns="http://ipower.org" elementFormDefault="qualified">
	
	<xs:element name="module">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="module" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="id" type="xs:string" use="required"/>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="uri" type="xs:string" use="optional"/>
			<xs:attribute name="order" type="xs:int" use="required"/>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="system">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="module" minOccurs="0" maxOccurs="unbounded"/>		
			</xs:sequence>
			<xs:attribute name="id" type="xs:string" use="required"/>
			<xs:attribute name="sign" type="xs:string" use="required"/>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="description" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="ipower">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="system" minOccurs="1" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="verion" type="xs:double" default="1.0" use="required"/>
		</xs:complexType>
	</xs:element>

</xs:schema>

=== jeasonyoung/studentbehaviors/src/main/resources/main_menus.xml
<?xml version="1.0" encoding="UTF-8"?>
<ipower verion="1.0" xmlns="http://ipower.org/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://ipower.org/ iPowerSchema.xsd ">
  <system id="AAA00000000000000000000000000000" sign="ipower.studentbehaviors" name="测试" description="学生日常管理系统">
  	<module id="AAA00000000000000000000000000001" name="系统设置" uri="" order="1">
  		<!--module id="AAA00000000000000000000000000101" name="学校信息" uri="/settings/school.action" order="1"/-->
  		<module id="AAA00000000000000000000000000201" name="教师管理" uri="/settings/teachers.action" order="2"/>
  		<module id="AAA00000000000000000000000000301" name="班级管理" uri="/settings/classes.action" order="3"/>
  		<module id="AAA00000000000000000000000000401" name="学生管理" uri="/settings/students.action" order="4"/>
  		<module id="AAA00000000000000000000000000501" name="班主任管理" uri="/settings/headmaster.action" order="5"/>
  		<module id="AAA00000000000000000000000000601" name="用户管理" uri="/settings/users.action" order="6"/>
  	</module>
	<module id="AAA00000000000000000000000000002" name="班主任" uri="" order="2">
		<!-- <module id="AAA00000000000000000000000000102" name="设置座位表" uri="" order="1"/> -->
		<module id="AAA00000000000000000000000000202" name="晨/午检登记" uri="/headmaster/attendance.action" order="2"/>
		<module id="AAA00000000000000000000000000302" name="查看本班登记" uri="" order="3"/>
	</module>
	<module id="AAA00000000000000000000000000003" name="校级管理" uri="" order="3">
		<module id="AAA00000000000000000000000000103" name="晨/午检登记" uri="" order="1"/>
	</module>
  </system>
</ipower>
